name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowSQL CLI
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
          bash snowsql-1.2.21-linux_x86_64.bash -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH

      - name: Run SQL in Snowflake
        env:
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          ~/.snowsql/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                             -u ${{ secrets.SNOWFLAKE_USER }} \
                             -d DEMO_DB \
                             -s PUBLIC \
                             -f snowflake/ddl/create_customer_table.sql
