name: Deploy to Snowflake using SnowSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Latest SnowSQL Version
        id: snowsql_version
        run: |
          # Fetch latest stable version info
          VERSION_JSON=$(curl -s https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.0/generic.js )
          eval $(echo "$VERSION_JSON" | grep -o 'snowSqlVersion="[^"]*"' | sed 's/snowSqlVersion="//;s/"$//')
          echo "Found SnowSQL version: $snowSqlVersion"
          echo "version=$snowSqlVersion" >> $GITHUB_OUTPUT

      - name: Download and Extract SnowSQL
        run: |
          mkdir -p ~/snowsql
          SNOWSQL_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/ ${{ steps.snowsql_version.outputs.version }}/linux_x86_64/snowsql-${{ steps.snowsql_version.outputs.version }}-linux_x86_64.tar.gz"
          curl -L "$SNOWSQL_URL" | tar -xz -C ~/snowsql
          echo "$HOME/snowsql" >> $GITHUB_PATH

      - name: Verify Installation
        run: |
          snowsql --version

      - name: Run SnowSQL Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowsql \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -p $SNOWFLAKE_PASSWORD \
            -d DEMO_DB -s PUBLIC \
            -f snowflake/ddl/create_customer_table.sql
