name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowSQL via pip
        run: |
          pip install snowflake-connector-python
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/scripts/installers/other/snowsql-linux_x86_64.bash
          bash snowsql-linux_x86_64.bash -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH

      - name: Run SQL in Snowflake
        run: |
          ~/.snowsql/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
                             -u ${{ secrets.SNOWFLAKE_USER }} \
                             -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
                             -d DEMO_DB \
                             -s PUBLIC \
                             -f snowflake/ddl/create_customer_table.sql
