name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowCLI (snowflake-cli-labs)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install snowflake-cli-labs

      - name: Run SQL in Snowflake using full path
        run: |
          echo "$SNOWFLAKE_PASSWORD" | ~/.local/bin/snowcli \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            sql run -f snowflake/ddl/create_customer_table.sql
