name: Deploy to Snowflake via Docker (SnowSQL)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run SnowSQL using Snowflake Docker Image
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          docker run --rm -v $PWD:/scripts -w /scripts \
            snowflake/snowsql:latest snowsql \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -p $SNOWFLAKE_PASSWORD \
            -d DEMO_DB -s PUBLIC \
            -f snowflake/ddl/create_customer_table.sql
