name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SnowCLI and add to PATH
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install snowflake-cli-labs
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run SQL in Snowflake using SnowCLI
        run: |
          echo "$SNOWFLAKE_PASSWORD" | snowcli \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            sql run -f snowflake/ddl/create_customer_table.sql
