name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snowflake CLI (snowcli)
        run: |
          pip install snowflake-cli-labs

      - name: Run SQL in Snowflake
        run: |
          echo "$SNOWFLAKE_PASSWORD" | snowcli \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --user ${{ secrets.SNOWFLAKE_USER }} \
            sql run -f snowflake/ddl/create_customer_table.sql
